import path from "node:path";
import type { Plugin } from "vite";

/**
 * Plugin to support Alloy Widgets
 */
export function widgetPlugin(appDir: string): Plugin {
  return {
    name: "titanium:alloy:widgets",
    /**
     * Resolves URLs generated by `WPATH` to their source files inside a
     * Widget's `lib` directory.
     *
     * @todo: Support Widgets from `node_modules`.
     */
    async resolveId(id, importer) {
      if (id.startsWith("#widget/")) {
        const widgetSourceId = createContextualWidgetSourceId(
          appDir,
          id,
          importer,
        );
        if (!widgetSourceId) return;

        const result = await this.resolve(widgetSourceId, importer, {
          skipSelf: true,
        });
        return result?.id;
      }

      if (id.startsWith("/") && !id.startsWith(appDir)) {
        // check WPATH generated url `/<widget>/<id>`
        const secondSlashIndex = id.indexOf("/", 1);
        if (secondSlashIndex !== -1) {
          const widgetId = id.slice(1, secondSlashIndex);
          const relativeId = id.slice(secondSlashIndex + 1);
          const result = await this.resolve(
            path.join(appDir, "widgets", widgetId, "lib", relativeId),
            importer,
            { skipSelf: true },
          );
          if (result) {
            return result.id;
          }
        }
      }
    },
  };
}

export function createContextualWidgetSourceId(
  appDir: string,
  id: string,
  importer: string | undefined,
): string | undefined {
  if (!id.startsWith("#widget/")) return undefined;

  const widgetId = getImporterWidgetId(appDir, importer);
  if (!widgetId) return undefined;

  return path.join(appDir, "widgets", widgetId, id.slice("#widget/".length));
}

function getImporterWidgetId(
  appDir: string,
  importer: string | undefined,
): string | undefined {
  if (!importer) return undefined;

  const relativeImporter = path.relative(appDir, importer).replace(/\\/g, "/");
  const prefix = "widgets/";
  if (!relativeImporter.startsWith(prefix)) return undefined;

  const remainder = relativeImporter.slice(prefix.length);
  const slashIndex = remainder.indexOf("/");
  if (slashIndex === -1) return undefined;

  return remainder.slice(0, slashIndex);
}
